'use strict';
// Compare ipv6-classify against vectors generated by Python's ipaddress
// (tests/vectors.json), plus hand-written checks for the things ipaddress does
// not model: tunnel detection and EUI-64 / MAC recovery.
//   node tests/run.js

const path = require('path');
const assert = require('assert');
const ip6 = require(path.join(__dirname, '..', 'ipv6-classify.js'));
const V = require(path.join(__dirname, 'vectors.json'));

let passed = 0;
const failures = [];

function check(label, fn) {
  try {
    fn();
    passed++;
  } catch (e) {
    failures.push(`${label}\n    ${e.message.split('\n').join('\n    ')}`);
  }
}

// ---------------------------------------------------------------------------
// 1. expand() must agree with ipaddress.exploded
// ---------------------------------------------------------------------------
for (const v of V.valid) {
  check(`expand ${v.input}`, () => {
    const g = ip6.expand(v.input);
    assert.ok(g, 'returned null');
    assert.strictEqual(g.join(':'), v.exploded);
  });
}

// ---------------------------------------------------------------------------
// 2. compress() must agree with str(ipaddress.IPv6Address) — RFC 5952
//
// This is the part that is easy to get subtly wrong: the longest zero run
// wins, the leftmost wins a tie, and a single zero group is never compressed.
// ---------------------------------------------------------------------------
for (const v of V.valid) {
  check(`compress ${v.input}`, () => {
    assert.strictEqual(ip6.compress(v.input), v.compressed);
  });
}

check('compress is idempotent', () => {
  for (const v of V.valid) {
    assert.strictEqual(ip6.compress(v.compressed), v.compressed);
  }
});

check('a single zero group is not compressed', () => {
  // ipaddress renders this as 1:2:3:4:5:6:0:8, not 1:2:3:4:5:6::8
  assert.strictEqual(ip6.compress('1:2:3:4:5:6:0:8'), '1:2:3:4:5:6:0:8');
});

check('the leftmost of two equal runs is compressed', () => {
  assert.strictEqual(ip6.compress('1:0:0:2:0:0:0:3'), '1:0:0:2::3');
});

// ---------------------------------------------------------------------------
// 3. Invalid addresses must be rejected, exactly as ipaddress rejects them
// ---------------------------------------------------------------------------
for (const bad of V.invalid) {
  check(`reject ${JSON.stringify(bad)}`, () => {
    assert.strictEqual(ip6.expand(bad), null, `accepted ${JSON.stringify(bad)}`);
    assert.strictEqual(ip6.classify(bad).type, 'unparseable');
  });
}

// ---------------------------------------------------------------------------
// 4. classify() against the flags ipaddress does expose
// ---------------------------------------------------------------------------
for (const v of V.valid) {
  const c = ip6.classify(v.input);

  if (v.is_loopback) {
    check(`${v.input} is loopback`, () => assert.strictEqual(c.type, 'loopback'));
  }
  if (v.is_link_local) {
    check(`${v.input} is link-local`, () => assert.strictEqual(c.type, 'link-local'));
  }
  if (v.is_multicast) {
    check(`${v.input} is multicast`, () => assert.strictEqual(c.type, 'multicast'));
  }
  // NOTE: ipaddress.is_global is registry-based - it means "not in a
  // special-purpose registry", so it is True for multicast (ff02::1) and for
  // unassigned space (1:0:0:2::3). It is NOT a synonym for global unicast, so
  // it is only used here in the direction that does hold.
  if (v.is_private) {
    check(`${v.input} is private, so never global unicast`, () => {
      assert.notStrictEqual(c.type, 'global unicast');
    });
  }
}

// Addresses that really are global unicast, asserted by hand.
for (const addr of ['2606:4700:4700::1111', '2001:4860:4860::8888',
                    '2a00:1450:4001:80e::200e', '2400:cb00:2048:1::c629:d7a2']) {
  check(`${addr} is global unicast`, () => {
    assert.strictEqual(ip6.classify(addr).type, 'global unicast');
    assert.strictEqual(ip6.isGlobal(addr), true);
  });
}

for (const addr of ['::1', '::', 'fe80::1', 'fd12:3456:789a:1::1', 'ff02::1',
                    '::ffff:1.2.3.4', '2001:db8::1']) {
  check(`${addr} is not global unicast`, () => {
    assert.strictEqual(ip6.isGlobal(addr), false);
  });
}

// ---------------------------------------------------------------------------
// 5. Tunnels, documentation and IPv4-mapped — not modelled by ipaddress
// ---------------------------------------------------------------------------
check('6to4 is called out as a tunnel', () => {
  assert.strictEqual(ip6.classify('2002:c000:204::').type, '6to4 tunnel');
});

check('Teredo is called out as a tunnel', () => {
  assert.strictEqual(
    ip6.classify('2001:0:4136:e378:8000:63bf:3fff:fdd2').type,
    'Teredo tunnel'
  );
});

check('the documentation range is not mistaken for a real address', () => {
  assert.strictEqual(ip6.classify('2001:db8::1').type, 'documentation');
});

check('IPv4-mapped is not reported as native IPv6', () => {
  assert.strictEqual(ip6.classify('::ffff:1.2.3.4').type, 'IPv4-mapped');
  assert.strictEqual(ip6.isGlobal('::ffff:1.2.3.4'), false);
});

check('the unspecified address is distinguished from loopback', () => {
  assert.strictEqual(ip6.classify('::').type, 'unspecified');
  assert.strictEqual(ip6.classify('::1').type, 'loopback');
});

// ---------------------------------------------------------------------------
// 6. EUI-64 and MAC recovery
//
// EUI-64 splits the six-byte MAC and inserts ff:fe in the middle, flipping the
// universal/local bit of the first byte. The MAC is not hashed or truncated —
// it is sitting in the address, which is the whole privacy problem.
// ---------------------------------------------------------------------------
const EUI = [
  // address,                               MAC it was built from
  ['fe80::0202:b3ff:fe1e:8329',             '00:02:b3:1e:83:29'],
  ['2001:db8::0212:34ff:fe56:7890',         '00:12:34:56:78:90'],
  ['fe80::021b:63ff:fe98:7654',             '00:1b:63:98:76:54']
];

for (const [addr, mac] of EUI) {
  check(`EUI-64 detected in ${addr}`, () => {
    assert.strictEqual(ip6.isEui64(addr), true);
  });
  check(`MAC recovered from ${addr}`, () => {
    assert.strictEqual(ip6.macFromEui64(addr), mac);
  });
}

check('a privacy-extension address is not EUI-64', () => {
  // random interface identifier: no ff:fe in the middle
  assert.strictEqual(ip6.isEui64('2001:db8::9c2a:7e41:bb03:1d5f'), false);
  assert.strictEqual(ip6.macFromEui64('2001:db8::9c2a:7e41:bb03:1d5f'), null);
});

check('ff:fe must be in the right position, not merely present', () => {
  // ff:fe present but in groups 4/5 rather than straddling 5/6
  assert.strictEqual(ip6.isEui64('2001:db8::fffe:1234:5678:9abc'), false);
});

check('macFromEui64 refuses junk', () => {
  assert.strictEqual(ip6.macFromEui64('not an address'), null);
  assert.strictEqual(ip6.macFromEui64('::1'), null);
});

// ---------------------------------------------------------------------------
// 7. Input handling
// ---------------------------------------------------------------------------
check('case and surrounding whitespace do not matter', () => {
  assert.strictEqual(ip6.compress('  2001:DB8::1  '), '2001:db8::1');
});

check('a zone index is ignored', () => {
  assert.strictEqual(ip6.classify('fe80::1%eth0').type, 'link-local');
  assert.strictEqual(ip6.compress('fe80::1%eth0'), 'fe80::1');
});

check('non-strings do not throw', () => {
  for (const v of [null, undefined, 42, {}, []]) {
    assert.strictEqual(ip6.expand(v), null);
    assert.strictEqual(ip6.classify(v).type, 'unparseable');
    assert.strictEqual(ip6.isEui64(v), false);
  }
});

// ---------------------------------------------------------------------------
console.log(`${passed} passed, ${failures.length} failed`);
if (failures.length) {
  console.log('');
  for (const f of failures) { console.log('  FAIL  ' + f); }
  process.exit(1);
}
